language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio lib install "PubSubClient"
    - platformio lib install "DHT sensor library"
    - platformio lib install "ArduinoJSON"
    - platformio lib install "ESP8266WebServer"
    - platformio lib install "ESP8266WiFi"
    - platformio lib install "WifiManager"
    - platformio lib install "DNSServer"
    - platformio lib install "DoubleResetDetector"
    
script:
    - platformio run
